#!/usr/bin/env bash
# Rebuilds sql/setup.sql from the numbered parts and loads it into MySQL.
# Usage (from the mealbridge folder):  bash tools/rebuild.sh
set -euo pipefail
cd "$(dirname "$0")/.."
python3 tools/gen_seed.py
{
  echo "-- ====================================================================="
  echo "-- MealBridge setup.sql : ONE file that builds the whole database."
  echo "-- Generated by tools/rebuild.sh from sql/01,03-08 (do not edit here;"
  echo "-- edit the numbered files and re-run). Run as a MySQL admin:"
  echo "--     mysql -u root -p < sql/setup.sql"
  echo "-- Drops and recreates the 'mealbridge' database and the 4 demo logins."
  echo "-- Contains SYNTHETIC data only."
  echo "-- ====================================================================="
  for f in 01_schema.sql 03_functions.sql 04_procedures.sql 05_triggers.sql \
           06_views.sql 07_seed_synthetic.sql 08_roles_grants.sql; do
    echo; echo "-- >>>>>>>>>>>>>>>>>>>> sql/$f <<<<<<<<<<<<<<<<<<<<"; echo
    cat "sql/$f"
  done
} > sql/setup.sql
mysql -uroot < sql/setup.sql > /dev/null
echo "setup.sql built and loaded: $(wc -l < sql/setup.sql) lines"
