-- =====================================================================
-- MealBridge : 20 analytical queries                    Stage 4 deliverable
-- Each query has a one-line purpose. Real output: 11_queries.output.md
-- (generated by tools/run_report.py). All data is SYNTHETIC.
--
-- Index of SQL features:
--   joins ............ Q1 Q2 Q4 Q15 Q19
--   nested/subquery .. Q3 (NOT EXISTS) Q7 (scalar) Q8 (correlated) Q16 (EXISTS)
--   aggregates ....... Q5 (ROLLUP) Q6 (HAVING) Q14 Q17 Q20
--   window functions . Q9 (RANK) Q10 (running SUM) Q11 (moving AVG)
--                      Q12 (LAG) Q13 (NTILE) Q18 (ROW_NUMBER)
--   spatial .......... Q2      CTEs ......... Q11 Q12 Q13 Q16 Q17
-- =====================================================================
USE mealbridge;

-- @@ Q1. Shelter's live feed, best match first (JOIN + function)
-- Purpose: what staff of "SYN Katpadi Night Shelter" (site 9) see right now: every available batch with its fair-match score for them, NULL = not eligible.
SELECT f.batch_id, f.mess, f.category, f.quantity_kg AS kg, f.meals_equiv AS meals,
       f.storage, f.minutes_left,
       fn_match_score(f.batch_id, 9, NOW()) AS my_match_score
  FROM v_live_feed f
 ORDER BY my_match_score IS NULL, my_match_score DESC;

-- @@ Q2. Shelters within 5 km of a mess, nearest first (spatial JOIN)
-- Purpose: the reachable neighbourhood of "SYN Mess A (Veg)", using great-circle distance on SRID 4326 points.
SELECT t.name AS shelter, sh.shelter_type,
       ROUND(ST_Distance_Sphere(m.location, t.location) / 1000, 2) AS km,
       ROUND(fn_travel_minutes(ST_Distance_Sphere(m.location, t.location) / 1000)) AS est_travel_min
  FROM site m
  JOIN site t     ON t.site_type = 'SHELTER' AND t.is_active
  JOIN shelter sh ON sh.site_id = t.site_id
 WHERE m.site_id = 1
   AND ST_Distance_Sphere(m.location, t.location) <= 5000
 ORDER BY km;

-- @@ Q3. Which shelters may receive a given batch? (nested NOT EXISTS)
-- Purpose: dietary suitability for the live chicken-curry batch: a shelter qualifies only if NONE of the batch's tags is on its exclusion list.
SELECT t.name AS shelter,
       (SELECT GROUP_CONCAT(tag_code) FROM shelter_diet_exclusion x
         WHERE x.shelter_site_id = s.site_id) AS excludes
  FROM shelter s JOIN site t ON t.site_id = s.site_id
 WHERE t.is_active
   AND NOT EXISTS (SELECT 1
                     FROM batch_diet_tag b
                     JOIN shelter_diet_exclusion e ON e.tag_code = b.tag_code
                    WHERE b.batch_id = (SELECT batch_id FROM surplus_batch
                                         WHERE description = 'SYN Chicken curry (live demo)')
                      AND e.shelter_site_id = s.site_id)
 ORDER BY shelter;

-- @@ Q4. Full journey of batches on one multi-stop trip (6-table JOIN)
-- Purpose: trace food from mess to shelter through claim, trip and volunteer, for the first trip that carried more than one batch.
SELECT b.batch_id, ms.name AS from_mess, ss.name AS to_shelter, u.full_name AS volunteer,
       b.created_at AS posted, c.claimed_at, sp.departed_at AS picked_up, sd.arrived_at AS dropped,
       c.status AS claim_status
  FROM trip_item ti
  JOIN claim c          ON c.claim_id = ti.claim_id
  JOIN surplus_batch b  ON b.batch_id = c.batch_id
  JOIN site ms          ON ms.site_id = b.mess_site_id
  JOIN site ss          ON ss.site_id = c.shelter_site_id
  JOIN pickup_trip pt   ON pt.trip_id = ti.trip_id
  JOIN app_user u       ON u.user_id = pt.volunteer_id
  JOIN trip_stop sp     ON sp.trip_id = ti.trip_id AND sp.stop_seq = ti.pickup_seq
  JOIN trip_stop sd     ON sd.trip_id = ti.trip_id AND sd.stop_seq = ti.drop_seq
 WHERE ti.trip_id = (SELECT trip_id FROM trip_item GROUP BY trip_id
                      HAVING COUNT(*) > 1 ORDER BY trip_id LIMIT 1)
 ORDER BY ti.pickup_seq;

-- @@ Q5. Surplus posted and rescued per mess and meal slot, with subtotals (GROUP BY ... WITH ROLLUP)
-- Purpose: where the surplus comes from; ROLLUP adds a per-mess subtotal row and a grand total (NULL slot / NULL mess).
SELECT IF(GROUPING(t.name), 'ALL MESSES', t.name)  AS mess,
       IF(GROUPING(b.meal_slot), '(all slots)', b.meal_slot) AS slot,
       COUNT(*)                                      AS batches,
       SUM(b.quantity_kg)                            AS kg_posted,
       SUM(IF(b.status = 'DELIVERED', b.quantity_kg, 0)) AS kg_rescued
  FROM surplus_batch b JOIN site t ON t.site_id = b.mess_site_id
 GROUP BY t.name, b.meal_slot WITH ROLLUP;

-- @@ Q6. Food categories losing more than 30% of their kg to expiry (aggregate + HAVING)
-- Purpose: tells the platform which kinds of food need faster handling or chilling.
SELECT fc.name AS category, fc.risk_level,
       COUNT(*)                                             AS batches,
       SUM(b.quantity_kg)                                   AS kg_posted,
       SUM(IF(b.status = 'EXPIRED', b.quantity_kg, 0))      AS kg_expired,
       ROUND(100 * SUM(IF(b.status = 'EXPIRED', b.quantity_kg, 0)) / SUM(b.quantity_kg), 1) AS pct_expired
  FROM surplus_batch b JOIN food_category fc ON fc.category_id = b.category_id
 GROUP BY fc.category_id, fc.name, fc.risk_level
HAVING pct_expired > 30
 ORDER BY pct_expired DESC;

-- @@ Q7. Messes whose average batch is larger than the platform average (scalar subquery)
-- Purpose: big-batch messes are the ones where whole-batch claiming may not fit small shelters; candidates for splitting batches.
SELECT t.name AS mess, COUNT(*) AS batches, ROUND(AVG(b.quantity_kg), 2) AS avg_batch_kg,
       (SELECT ROUND(AVG(quantity_kg), 2) FROM surplus_batch) AS platform_avg_kg
  FROM surplus_batch b JOIN site t ON t.site_id = b.mess_site_id
 GROUP BY t.name
HAVING AVG(b.quantity_kg) > (SELECT AVG(quantity_kg) FROM surplus_batch)
 ORDER BY avg_batch_kg DESC;

-- @@ Q8. Each mess's worst weekday for leftovers (correlated subquery)
-- Purpose: the inner query is re-evaluated for every mess (it references the outer row), returning that mess's weekday with the highest average leftover.
SELECT t.name AS mess,
       (SELECT DAYNAME(l2.service_date)
          FROM mess_meal_log l2
         WHERE l2.mess_site_id = m.site_id
         GROUP BY DAYNAME(l2.service_date)
         ORDER BY AVG(l2.leftover_kg) DESC LIMIT 1) AS worst_weekday,
       (SELECT ROUND(AVG(l3.leftover_kg), 1) FROM mess_meal_log l3
         WHERE l3.mess_site_id = m.site_id)           AS avg_leftover_kg_per_meal
  FROM mess m JOIN site t ON t.site_id = m.site_id
 ORDER BY t.name;

-- @@ Q9. Shelters ranked by food received in the last 30 days (RANK window)
-- Purpose: RANK() and the share of total (SUM() OVER ()) show at a glance whether a few shelters dominate.
SELECT t.name AS shelter, s.beneficiary_count AS beneficiaries,
       SUM(b.quantity_kg)                                    AS kg_received,
       RANK() OVER (ORDER BY SUM(b.quantity_kg) DESC)        AS rank_kg,
       ROUND(100 * SUM(b.quantity_kg) / SUM(SUM(b.quantity_kg)) OVER (), 1) AS pct_of_all,
       RANK() OVER (ORDER BY SUM(b.quantity_kg) / s.beneficiary_count DESC) AS rank_kg_per_person
  FROM claim c
  JOIN surplus_batch b ON b.batch_id = c.batch_id
  JOIN shelter s       ON s.site_id = c.shelter_site_id
  JOIN site t          ON t.site_id = s.site_id
 WHERE c.status = 'FULFILLED' AND c.claimed_at >= NOW() - INTERVAL 30 DAY
 GROUP BY t.name, s.beneficiary_count
 ORDER BY rank_kg;

-- @@ Q10. Cumulative meals saved, day by day (running SUM window)
-- Purpose: the "meals saved" counter of the impact dashboard as a growing curve.
SELECT day, meals_saved,
       SUM(meals_saved) OVER (ORDER BY day ROWS UNBOUNDED PRECEDING) AS cumulative_meals_saved,
       SUM(kg_delivered) OVER (ORDER BY day ROWS UNBOUNDED PRECEDING) AS cumulative_kg
  FROM v_impact_daily
 ORDER BY day;

-- @@ Q11. Surplus peaks: days above 1.3x the 7-day moving average (moving AVG window + CTE)
-- Purpose: finds the peak days (weekends, the long weekend) that need extra shelters and volunteers on standby.
WITH daily AS (
  SELECT DATE(created_at) AS day, DAYNAME(created_at) AS weekday, SUM(quantity_kg) AS kg_posted
    FROM surplus_batch GROUP BY DATE(created_at), DAYNAME(created_at)
), ma AS (
  SELECT day, weekday, kg_posted,
         ROUND(AVG(kg_posted) OVER (ORDER BY day ROWS BETWEEN 6 PRECEDING AND CURRENT ROW), 1) AS ma7
    FROM daily
)
SELECT day, weekday, kg_posted, ma7,
       IF(kg_posted > 1.3 * ma7, 'PEAK', '') AS flag
  FROM ma ORDER BY day;

-- @@ Q12. Week-over-week change in surplus per mess (LAG window)
-- Purpose: LAG() reads the previous week's value of the same mess, so each mess's trend is visible without a self-join.
WITH weekly AS (
  SELECT t.name AS mess, YEARWEEK(b.created_at, 3) AS iso_week, SUM(b.quantity_kg) AS kg
    FROM surplus_batch b JOIN site t ON t.site_id = b.mess_site_id
   WHERE b.description NOT LIKE '%(live demo)'
   GROUP BY t.name, YEARWEEK(b.created_at, 3)
)
SELECT mess, iso_week, kg,
       LAG(kg) OVER (PARTITION BY mess ORDER BY iso_week)        AS prev_week_kg,
       ROUND(100 * (kg - LAG(kg) OVER (PARTITION BY mess ORDER BY iso_week))
             / LAG(kg) OVER (PARTITION BY mess ORDER BY iso_week), 1) AS pct_change
  FROM weekly ORDER BY mess, iso_week;

-- @@ Q13. Response-time quartiles by meal slot (NTILE window)
-- Purpose: NTILE(4) splits all claims into four equal groups by response time; counting slots per quartile shows that late (dinner) posts get the slowest answers.
WITH r AS (
  SELECT b.meal_slot, TIMESTAMPDIFF(MINUTE, b.created_at, c.claimed_at) AS response_min,
         NTILE(4) OVER (ORDER BY TIMESTAMPDIFF(SECOND, b.created_at, c.claimed_at)) AS quartile
    FROM claim c JOIN surplus_batch b ON b.batch_id = c.batch_id
)
SELECT quartile, MIN(response_min) AS from_min, MAX(response_min) AS to_min,
       SUM(meal_slot = 'BREAKFAST') AS breakfast, SUM(meal_slot = 'LUNCH') AS lunch,
       SUM(meal_slot = 'SNACKS') AS snacks, SUM(meal_slot = 'DINNER') AS dinner
  FROM r GROUP BY quartile ORDER BY quartile;

-- @@ Q14. Rescue rate by storage mode (conditional aggregation)
-- Purpose: the case for the perishability clock: on this synthetic data, chilled food has a far longer safe window and is rescued far more often.
SELECT storage, COUNT(*) AS batches,
       ROUND(AVG(TIMESTAMPDIFF(MINUTE, created_at, safe_until))) AS avg_window_min,
       SUM(status = 'DELIVERED') AS delivered, SUM(status = 'EXPIRED') AS expired,
       ROUND(100 * SUM(status = 'DELIVERED') / COUNT(*), 1) AS rescue_rate_pct
  FROM surplus_batch
 WHERE description NOT LIKE '%(live demo)'
 GROUP BY storage ORDER BY rescue_rate_pct DESC;

-- @@ Q15. Volunteer workload, including volunteers with no trips (LEFT JOIN)
-- Purpose: LEFT JOIN keeps volunteers who never drove (unverified or unavailable), which an INNER JOIN would silently drop.
SELECT u.full_name AS volunteer, v.vehicle_type, v.max_load_kg,
       IF(v.verified_at IS NULL, 'NOT VERIFIED', 'verified') AS id_check,
       COUNT(DISTINCT pt.trip_id)                             AS trips,
       COUNT(ti.claim_id)                                     AS batches_carried,
       COALESCE(SUM(b.quantity_kg), 0)                        AS kg_carried,
       COUNT(DISTINCT IF(pt.trip_id IN (SELECT trip_id FROM trip_item GROUP BY trip_id HAVING COUNT(*) > 1),
                         pt.trip_id, NULL))                   AS multi_stop_trips
  FROM volunteer v
  JOIN app_user u          ON u.user_id = v.user_id
  LEFT JOIN pickup_trip pt ON pt.volunteer_id = v.user_id
  LEFT JOIN trip_item ti   ON ti.trip_id = pt.trip_id
  LEFT JOIN claim c        ON c.claim_id = ti.claim_id
  LEFT JOIN surplus_batch b ON b.batch_id = c.batch_id
 GROUP BY u.full_name, v.vehicle_type, v.max_load_kg, v.verified_at
 ORDER BY kg_carried DESC;

-- @@ Q16. Missed opportunities: expired batches that DID have an eligible shelter when posted (EXISTS)
-- Purpose: separates "nobody could take it" from "someone could have, but nobody acted in time": the second group is what faster alerts would save.
WITH exp AS (
  SELECT b.batch_id, b.meal_slot, b.storage, b.quantity_kg,
         EXISTS (SELECT 1 FROM shelter s
                  WHERE fn_match_score(b.batch_id, s.site_id, b.created_at) IS NOT NULL) AS had_match
    FROM surplus_batch b
   WHERE b.status = 'EXPIRED'
)
SELECT meal_slot,
       COUNT(*)                         AS expired_batches,
       SUM(had_match)                   AS had_eligible_shelter,
       SUM(NOT had_match)               AS no_shelter_possible,
       SUM(IF(had_match, quantity_kg, 0)) AS kg_saveable
  FROM exp GROUP BY meal_slot ORDER BY expired_batches DESC;

-- @@ Q17. Forecast accuracy over the last 7 forecast days (JOIN forecast to actual)
-- Purpose: mean absolute error of the WEEKDAY_MA_4W forecast per mess, the honest test of whether pre-alerts are worth sending.
SELECT t.name AS mess,
       COUNT(*)                                        AS forecasts,
       ROUND(AVG(l.leftover_kg), 1)                    AS avg_actual_kg,
       ROUND(AVG(f.predicted_kg), 1)                   AS avg_predicted_kg,
       ROUND(AVG(ABS(f.predicted_kg - l.leftover_kg)), 1) AS mae_kg,
       ROUND(100 * AVG(ABS(f.predicted_kg - l.leftover_kg)) / AVG(l.leftover_kg), 1) AS mae_pct
  FROM surplus_forecast f
  JOIN mess_meal_log l ON l.mess_site_id = f.mess_site_id
                      AND l.service_date = f.forecast_date AND l.meal_slot = f.meal_slot
  JOIN site t          ON t.site_id = f.mess_site_id
 WHERE f.method = 'WEEKDAY_MA_4W'
 GROUP BY t.name ORDER BY mae_pct;

-- @@ Q18. Latest three custody events per batch, for today's live batches (ROW_NUMBER window)
-- Purpose: "top-N per group": ROW_NUMBER() restarts for every batch (PARTITION BY), so the outer filter keeps each batch's newest 3 events; the hash column shows the chain link.
SELECT batch_id, rn, event_type, event_time, LEFT(row_hash, 12) AS hash_prefix,
       LEFT(prev_hash, 12) AS prev_prefix
  FROM (SELECT e.*, ROW_NUMBER() OVER (PARTITION BY e.batch_id ORDER BY e.event_id DESC) AS rn
          FROM custody_event e
          JOIN surplus_batch b ON b.batch_id = e.batch_id
         WHERE b.description LIKE '%(live demo)') x
 WHERE rn <= 3
 ORDER BY batch_id, rn;

-- @@ Q19. Dishes that leave the most surplus when served (M:N JOIN through mess_menu)
-- Purpose: a forecasting feature: average leftover of the meals in which each dish was on the menu.
SELECT mi.name AS dish, fc.name AS category,
       COUNT(*)                     AS times_served,
       ROUND(AVG(l.leftover_kg), 1) AS avg_leftover_kg_of_meal,
       ROUND(AVG(100 * l.leftover_kg / l.prepared_kg), 1) AS avg_leftover_pct
  FROM mess_menu mm
  JOIN menu_item mi     ON mi.menu_item_id = mm.menu_item_id
  JOIN food_category fc ON fc.category_id = mi.category_id
  JOIN mess_meal_log l  ON l.mess_site_id = mm.mess_site_id
                       AND l.service_date = mm.service_date AND l.meal_slot = mm.meal_slot
 GROUP BY mi.name, fc.name
HAVING times_served >= 10
 ORDER BY avg_leftover_pct DESC LIMIT 8;

-- @@ Q20. Custody chain integrity across the whole database (function in aggregate)
-- Purpose: re-computes every SHA-256 link of every batch's chain of custody; 0 broken chains = no record was altered.
SELECT COUNT(*)                                            AS batches_checked,
       (SELECT COUNT(*) FROM custody_event)                AS events_checked,
       SUM(fn_custody_first_bad_event(batch_id) <> 0)      AS broken_chains
  FROM surplus_batch;
